language: node_js
node_js: '10'
script:
    - npm install
    - npm run gh-pages
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true,
    local-dir: gh-pages
    on:
        branch: master
